In [2]:
import pandas as pd
import numpy as np
import requests

from pathlib import Path

PROJECT_ROOT = Path("../")

RAW_DATA = PROJECT_ROOT/"data"/"raw"

GRID_PATH = RAW_DATA/"grid_demand"
WEATHER_PATH = RAW_DATA/"weather"
CARBON_PATH = RAW_DATA/"carbon_data"

print(GRID_PATH)
print(WEATHER_PATH)
print(CARBON_PATH)

..\data\raw\grid_demand
..\data\raw\weather
..\data\raw\carbon_data

In [3]:
import pandas as pd

grid = pd.read_csv(
    "../data/raw/grid_demand/time_series_60min_singleindex_filtered.csv"
)

print(grid.shape)

grid.columns.tolist()

(50401, 43)

['utc_timestamp',
 'cet_cest_timestamp',
 'DE_load_actual_entsoe_transparency',
 'DE_load_forecast_entsoe_transparency',
 'DE_solar_capacity',
 'DE_solar_generation_actual',
 'DE_solar_profile',
 'DE_wind_capacity',
 'DE_wind_generation_actual',
 'DE_wind_profile',
 'DE_wind_offshore_capacity',
 'DE_wind_offshore_generation_actual',
 'DE_wind_offshore_profile',
 'DE_wind_onshore_capacity',
 'DE_wind_onshore_generation_actual',
 'DE_wind_onshore_profile',
 'DE_50hertz_load_actual_entsoe_transparency',
 'DE_50hertz_load_forecast_entsoe_transparency',
 'DE_50hertz_solar_generation_actual',
 'DE_50hertz_wind_generation_actual',
 'DE_50hertz_wind_offshore_generation_actual',
 'DE_50hertz_wind_onshore_generation_actual',
 'DE_LU_load_actual_entsoe_transparency',
 'DE_LU_load_forecast_entsoe_transparency',
 'DE_LU_price_day_ahead',
 'DE_LU_solar_generation_actual',
 'DE_LU_wind_generation_actual',
 'DE_LU_wind_offshore_generation_actual',
 'DE_LU_wind_onshore_generation_actual',
 'DE_amprion_load_actual_entsoe_transparency',
 'DE_amprion_load_forecast_entsoe_transparency',
 'DE_amprion_solar_generation_actual',
 'DE_amprion_wind_onshore_generation_actual',
 'DE_tennet_load_actual_entsoe_transparency',
 'DE_tennet_load_forecast_entsoe_transparency',
 'DE_tennet_solar_generation_actual',
 'DE_tennet_wind_generation_actual',
 'DE_tennet_wind_offshore_generation_actual',
 'DE_tennet_wind_onshore_generation_actual',
 'DE_transnetbw_load_actual_entsoe_transparency',
 'DE_transnetbw_load_forecast_entsoe_transparency',
 'DE_transnetbw_solar_generation_actual',
 'DE_transnetbw_wind_onshore_generation_actual']

In [4]:
selected_cols = [
    'utc_timestamp',
    'DE_load_actual_entsoe_transparency',
    'DE_solar_generation_actual',
    'DE_wind_generation_actual',
    'DE_solar_capacity',
    'DE_wind_capacity',
    'DE_LU_price_day_ahead'
]

grid_selected = grid[selected_cols]

grid_selected.head()

,utc_timestamp,DE_load_actual_entsoe_transparency,DE_solar_generation_actual,DE_wind_generation_actual,DE_solar_capacity,DE_wind_capacity,DE_LU_price_day_ahead
0,2014-12-31T23:00:00Z,NaN,NaN,NaN,37248.0,27913.0,NaN
1,2015-01-01T00:00:00Z,41151.0,NaN,8852.0,37248.0,27913.0,NaN
2,2015-01-01T01:00:00Z,40135.0,NaN,9054.0,37248.0,27913.0,NaN
3,2015-01-01T02:00:00Z,39106.0,NaN,9070.0,37248.0,27913.0,NaN
4,2015-01-01T03:00:00Z,38765.0,NaN,9163.0,37248.0,27913.0,NaN

In [5]:
grid_selected.info()

<class 'pandas.DataFrame'>
RangeIndex: 50401 entries, 0 to 50400
Data columns (total 7 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   utc_timestamp                       50401 non-null  str
 1   DE_load_actual_entsoe_transparency  50400 non-null  float64
 2   DE_solar_generation_actual          50297 non-null  float64
 3   DE_wind_generation_actual           50326 non-null  float64
 4   DE_solar_capacity                   43800 non-null  float64
 5   DE_wind_capacity                    43800 non-null  float64
 6   DE_LU_price_day_ahead               17540 non-null  float64
dtypes: float64(6), str(1)
memory usage: 2.7 MB

In [6]:
missing_pct = (
    grid_selected
    .isnull()
    .sum()
    / len(grid_selected)
    * 100
)

missing_pct.sort_values(
    ascending=False
)

DE_LU_price_day_ahead                 65.199103
DE_solar_capacity                     13.096962
DE_wind_capacity                      13.096962
DE_solar_generation_actual             0.206345
DE_wind_generation_actual              0.148807
DE_load_actual_entsoe_transparency     0.001984
utc_timestamp                          0.000000
dtype: float64

In [7]:
grid_selected.describe()

,DE_load_actual_entsoe_transparency,DE_solar_generation_actual,DE_wind_generation_actual,DE_solar_capacity,DE_wind_capacity,DE_LU_price_day_ahead
count,50400.000000,50297.000000,50326.000000,43800.000000,43800.000000,17540.000000
mean,55492.468552,4566.042905,11552.234650,42378.015114,39972.606758,35.809288
std,10015.431042,6940.267590,9076.350769,4306.391773,7262.785787,18.137177
min,31307.000000,0.000000,135.000000,37248.000000,27913.000000,-90.010000
25%,47106.000000,0.000000,4506.000000,38810.000000,33737.000000,26.717500
50%,55092.000000,173.000000,9015.000000,40941.000000,39808.000000,36.150000
75%,64309.250000,7342.000000,16113.750000,46092.000000,47730.000000,46.030000
max,77549.000000,32947.000000,46064.000000,50508.000000,50452.000000,200.040000